# Site settings
title: "About"
description: "Selahattin Can Özcan — Researcher at Columbia University"
author: "Can Özcan"
email: so2716@cumc.columbia.edu
baseurl: ""
url: "https://scanozcan.github.io"

# Social links
github_username: scanozcan

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigation
header_pages:
  - index.md
  - resume.md
  - publications.md
  - blog.md

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
